### Generated by rprotoc. DO NOT EDIT!
### <proto file: protos/protobuf/rpc/messages/error.proto>
# syntax = "proto2";
#
# package protobuf.rpc.messages;
#
# message Error {
#     required string error_class = 1;
#     optional string error_message = 2;
#     optional string error_backtrace = 3;
# }


module Protobuf
  module Rpc
    module Messages
      class Error < ::Protobuf::Message
        required :string, :error_class, 1
        optional :string, :error_message, 2
        repeated :string, :error_backtrace, 3
      end
    end
  end
end
