### Generated by rprotoc. DO NOT EDIT!
### <proto file: protos/protobuf/rpc/messages/rpc_compressed_message.proto>
# syntax = "proto2";
# 
# package protobuf.rpc.messages;
# 
# message RpcCompressedMessage {
#     optional bool compressed = 1 [default = true];
#     optional string response_type = 2;
#     required bytes response_body = 3;
# 
#     enum Serializer{
#         RAW = 0;
#         MSGPACK = 1;
#         YAML = 2;
#         JSON = 3;
#         MARSHAL = 4;
#     }
#     optional Serializer serializer = 4 [default = 1];
# }


module Protobuf
  module Rpc
    module Messages
      class RpcCompressedMessage < ::Protobuf::Message
        optional :bool, :compressed, 1, :default => true
        optional :string, :response_type, 2
        required :bytes, :response_body, 3
        class Serializer < ::Protobuf::Enum
          set_option :allow_alias
          define :RAW, 0
          define :MSGPACK, 1
          define :YAML, 2
          define :JSON, 3
          define :MARSHAL, 4
        end
        optional Serializer, :serializer, 4, :default => 1
      end
    end
  end
end

